"""empty message

Revision ID: 3fcf2d728441
Revises: b7bbc94ffc23
Create Date: 2023-05-17 18:08:45.646545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fcf2d728441'
down_revision = 'b7bbc94ffc23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('cart_id', type_='foreignkey')
        batch_op.drop_column('cart_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('cart_id', 'carts', ['cart_id'], ['id'])

    # ### end Alembic commands ###