"""empty message

Revision ID: b8a0cff2d7a5
Revises: b6a7a3133963
Create Date: 2023-05-18 18:30:14.341504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8a0cff2d7a5'
down_revision = 'b6a7a3133963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('cart_id', type_='foreignkey')
        batch_op.drop_column('cart_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('cart_id', 'carts', ['cart_id'], ['id'])

    # ### end Alembic commands ###