"""empty message

Revision ID: b7bbc94ffc23
Revises: 730c4ee79552
Create Date: 2023-05-17 10:47:58.488610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7bbc94ffc23'
down_revision = '730c4ee79552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('item_id')
        batch_op.drop_column('ticket_id')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', sa.Integer(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_foreign_key('cart_id', 'carts', ['cart_id'], ['id'])

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('cart_id', 'carts', ['cart_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint('cart_id', type_='foreignkey')
        batch_op.drop_column('cart_id')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('cart_id', type_='foreignkey')
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('cart_id')

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
